apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp.falco
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - psp.falco
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp.falco
roleRef:
  kind: Role
  name: psp.falco
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: falco
