apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-exporter
  labels:
    app.kubernetes.io/name: falco-exporter
    app.kubernetes.io/instance: falco-exporter
    app.kubernetes.io/version: "0.7.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: falco-exporter-0.8.0
  namespace: default
---
