apiVersion: v1
kind: ServiceAccount
metadata:
  name: falco-exporter
  labels:
    app.kubernetes.io/name: falco-exporter
    app.kubernetes.io/instance: falco-exporter
    app.kubernetes.io/version: "0.6.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: falco-exporter-0.7.1
  namespace: default
---
