apiVersion: apps/v1
kind: Deployment
metadata:
  name: falcosidekick
  namespace: default
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: falcosidekick-0.4.5
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: falcosidekick
      app.kubernetes.io/instance: falcosidekick
  template:
    metadata:
      labels:
        app.kubernetes.io/name: falcosidekick
        app.kubernetes.io/instance: falcosidekick
      annotations:
        checksum/config: 4b81542a63e72c0cde2eb3e9ea1814c2fe5420da850c2d5f3e84bb55548639d1
    spec:
      serviceAccountName: falcosidekick
      securityContext:
        runAsUser: 1234
        fsGroup: 1234
      containers:
        - name: falcosidekick
          image: "docker.io/falcosecurity/falcosidekick:2.24.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 2801
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          envFrom:
            - secretRef:
                name: falcosidekick
          env:
            - name: DEBUG
              value: "false"
            - name: CUSTOMFIELDS
              value: ""
            - name: MUTUALTLSFILESPATH
              value: "/etc/certs"
          resources:
            {}
