apiVersion: v1
kind: ServiceAccount
metadata:
  name: falcosidekick-ui
  namespace: default
  labels:
    app.kubernetes.io/name: falcosidekick-ui
    helm.sh/chart: falcosidekick-0.5.2
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: falcosidekick-ui
  namespace: default
  labels:
    app.kubernetes.io/name: falcosidekick-ui
    helm.sh/chart: falcosidekick-0.5.2
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: falcosidekick-ui
  namespace: default
  labels:
    app.kubernetes.io/name: falcosidekick-ui
    helm.sh/chart: falcosidekick-0.5.2
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: falcosidekick-ui
subjects:
- kind: ServiceAccount
  name: falcosidekick-ui
---
