apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick
  namespace: default
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: falcosidekick-0.4.3
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  # Slack Output
  SLACK_WEBHOOKURL: ""
  SLACK_OUTPUTFORMAT: "YWxs"
  SLACK_FOOTER: ""
  SLACK_ICON: ""
  SLACK_USERNAME: ""
  SLACK_MINIMUMPRIORITY: ""
  SLACK_MESSAGEFORMAT: ""

  # RocketChat Output
  ROCKETCHAT_WEBHOOKURL: ""
  ROCKETCHAT_OUTPUTFORMAT: "YWxs"
  ROCKETCHAT_ICON: ""
  ROCKETCHAT_USERNAME: ""
  ROCKETCHAT_MINIMUMPRIORITY: ""
  ROCKETCHAT_MESSAGEFORMAT: ""
  ROCKETCHAT_MUTUALTLS: "ZmFsc2U="
  ROCKETCHAT_CHECKCERT: "dHJ1ZQ=="

  # Mattermost Output
  MATTERMOST_WEBHOOKURL: ""
  MATTERMOST_OUTPUTFORMAT: "YWxs"
  MATTERMOST_FOOTER: ""
  MATTERMOST_ICON: ""
  MATTERMOST_USERNAME: ""
  MATTERMOST_MINIMUMPRIORITY: ""
  MATTERMOST_MESSAGEFORMAT: ""
  MATTERMOST_MUTUALTLS: "ZmFsc2U="
  MATTERMOST_CHECKCERT: "dHJ1ZQ=="

  # Teams Output
  TEAMS_WEBHOOKURL: ""
  TEAMS_OUTPUTFORMAT: "YWxs"
  TEAMS_ACTIVITYIMAGE: ""
  TEAMS_MINIMUMPRIORITY: ""

  # Datadog Output
  DATADOG_APIKEY: ""
  DATADOG_HOST: ""
  DATADOG_MINIMUMPRIORITY: ""

  # AlertManager Output
  ALERTMANAGER_HOSTPORT: ""
  ALERTMANAGER_MINIMUMPRIORITY: ""
  ALERTMANAGER_MUTUALTLS: "ZmFsc2U="
  ALERTMANAGER_CHECKCERT: "dHJ1ZQ=="

  # InfluxDB Output
  INFLUXDB_USER: ""
  INFLUXDB_PASSWORD: ""
  INFLUXDB_HOSTPORT: ""
  INFLUXDB_MINIMUMPRIORITY: ""
  INFLUXDB_DATABASE: "ZmFsY28="
  INFLUXDB_MUTUALTLS: "ZmFsc2U="
  INFLUXDB_CHECKCERT: "dHJ1ZQ=="

  # AWS Output
  AWS_ACCESSKEYID: ""
  AWS_SECRETACCESSKEY: ""
  AWS_REGION: ""
  AWS_LAMBDA_FUNCTIONNAME: ""
  AWS_LAMBDA_MINIMUMPRIORITY: ""
  AWS_CLOUDWATCHLOGS_LOGGROUP: ""
  AWS_CLOUDWATCHLOGS_LOGSTREAM: ""
  AWS_CLOUDWATCHLOGS_MINIMUMPRIORITY: ""
  AWS_SNS_TOPICARN: ""
  AWS_SNS_RAWJSON: "ZmFsc2U="
  AWS_SNS_MINIMUMPRIORITY: ""
  AWS_SQS_URL: ""
  AWS_SQS_MINIMUMPRIORITY: ""
  AWS_S3_BUCKET: ""
  AWS_S3_PREFIX: ""
  AWS_S3_MINIMUMPRIORITY: ""

  # SMTP Output
  SMTP_USER: ""
  SMTP_PASSWORD: ""
  SMTP_HOSTPORT: ""
  SMTP_FROM: ""
  SMTP_TO: ""
  SMTP_OUTPUTFORMAT: "aHRtbA=="
  SMTP_MINIMUMPRIORITY: ""

  # OpsGenie Output
  OPSGENIE_APIKEY: ""
  OPSGENIE_REGION: ""
  OPSGENIE_MINIMUMPRIORITY: ""
  OPSGENIE_MUTUALTLS: "ZmFsc2U="
  OPSGENIE_CHECKCERT: "dHJ1ZQ=="

  # Discord Output
  DISCORD_WEBHOOKURL: ""
  DISCORD_ICON: ""
  DISCORD_MINIMUMPRIORITY: ""

  # GCP Output
  GCP_CREDENTIALS: ""
  GCP_PUBSUB_PROJECTID: ""
  GCP_PUBSUB_TOPIC: ""
  GCP_PUBSUB_MINIMUMPRIORITY: ""
  GCP_STORAGE_BUCKET: ""
  GCP_STORAGE_PREFIX: ""
  GCP_STORAGE_MINIMUMPRIORITY: "ZGVidWc="
  GCP_CLOUDFUNCTIONS_NAME: ""
  GCP_CLOUDFUNCTIONS_MINIMUMPRIORITY: ""
  GCP_CLOUDRUN_ENDPOINT: ""
  GCP_CLOUDRUN_JWT: ""
  GCP_CLOUDRUN_MINIMUMPRIORITY: ""

  # GoogleChat Output
  GOOGLECHAT_WEBHOOKURL: ""
  GOOGLECHAT_OUTPUTFORMAT: "YWxs"
  GOOGLECHAT_MINIMUMPRIORITY: ""
  GOOGLECHAT_MESSAGEFORMAT: ""

  # ElasticSearch Output
  ELASTICSEARCH_HOSTPORT: ""
  ELASTICSEARCH_INDEX: "ZmFsY28="
  ELASTICSEARCH_TYPE: "ZXZlbnQ="
  ELASTICSEARCH_MINIMUMPRIORITY: ""
  ELASTICSEARCH_MUTUALTLS: "ZmFsc2U="
  ELASTICSEARCH_CHECKCERT: "dHJ1ZQ=="
  ELASTICSEARCH_USERNAME: ""
  ELASTICSEARCH_PASSWORD: ""

  # Loki Output
  LOKI_HOSTPORT: ""
  LOKI_MINIMUMPRIORITY: ""
  LOKI_MUTUALTLS: "ZmFsc2U="
  LOKI_CHECKCERT: "dHJ1ZQ=="

  # Nats Output
  NATS_HOSTPORT: ""
  NATS_MINIMUMPRIORITY: ""
  NATS_MUTUALTLS: "ZmFsc2U="
  NATS_CHECKCERT: "dHJ1ZQ=="

  # Stan Output
  STAN_HOSTPORT: ""
  STAN_CLUSTERID: ""
  STAN_CLIENTID: ""
  STAN_MINIMUMPRIORITY: ""
  STAN_MUTUALTLS: "ZmFsc2U="
  STAN_CHECKCERT: "dHJ1ZQ=="

  # Statsd
  STATSD_FORWARDER: ""
  STATSD_NAMESPACE: "ZmFsY29zaWRla2ljay4="

  # Dogstatsd
  DOGSTATSD_FORWARDER: ""
  DOGSTATSD_NAMESPACE: "ZmFsY29zaWRla2ljay4="
  DOGSTATSD_TAGS: ""

  # WebHook Output
  WEBHOOK_ADDRESS: ""
  WEBHOOK_CUSTOMHEADERS: ""
  WEBHOOK_MINIMUMPRIORITY: ""
  WEBHOOK_MUTUALTLS: "ZmFsc2U="
  WEBHOOK_CHECKCERT: "dHJ1ZQ=="

  # Azure Output
  AZURE_EVENTHUB_NAME: ""
  AZURE_EVENTHUB_NAMESPACE: ""
  AZURE_EVENTHUB_MINIMUMPRIORITY: ""

  # Kafka Output
  KAFKA_HOSTPORT: ""
  KAFKA_TOPIC: ""
  KAFKA_PARTITION: "MA=="
  KAFKA_MINIMUMPRIORITY: ""

  # PagerDuty Output
  PAGERDUTY_ROUTINGKEY: ""
  PAGERDUTY_MINIMUMPRIORITY: ""

  # Kubeless Output
  KUBELESS_FUNCTION: ""
  KUBELESS_NAMESPACE: ""
  KUBELESS_PORT: "ODA4MA=="
  KUBELESS_MINIMUMPRIORITY: ""
  KUBELESS_MUTUALTLS: "ZmFsc2U="
  KUBELESS_CHECKCERT: "dHJ1ZQ=="

  # OpenFaaS
  OPENFAAS_GATEWAYNAMESPACE: "b3BlbmZhYXM="
  OPENFAAS_GATEWAYSERVICE: "Z2F0ZXdheQ=="
  OPENFAAS_FUNCTIONNAME: ""
  OPENFAAS_FUNCTIONNAMESPACE: "b3BlbmZhYXMtZm4="
  OPENFAAS_GATEWAYPORT: "ODA4MA=="
  OPENFAAS_MINIMUMPRIORITY: ""
  OPENFAAS_MUTUALTLS: "ZmFsc2U="
  OPENFAAS_CHECKCERT: "dHJ1ZQ=="

  # Cloud Events Output
  CLOUDEVENTS_ADDRESS: ""
  CLOUDEVENTS_EXTENSION: ""
  CLOUDEVENTS_MINIMUMPRIORITY: ""

  # RabbitMQ Output
  RABBITMQ_URL: ""
  RABBITMQ_QUEUE: ""
  RABBITMQ_MINIMUMPRIORITY: "ZGVidWc="

  # Wavefront Output
  WAVEFRONT_ENDPOINTTYPE: ""
  WAVEFRONT_ENDPOINTHOST: ""
  WAVEFRONT_ENDPOINTTOKEN: ""
  WAVEFRONT_ENDPOINTMETRICPORT: "Mjg3OA=="
  WAVEFRONT_FLUSHINTERVALSECONDS: "MQ=="
  WAVEFRONT_BATCHSIZE: "MTAwMDA="
  WAVEFRONT_METRICNAME: "ZmFsY28uYWxlcnQ="
  WAVEFRONT_MINIMUMPRIORITY: "ZGVidWc="

  # Grafana Output
  GRAFANA_HOSTPORT: ""
  GRAFANA_APIKEY: ""
  GRAFANA_DASHBOARDID: ""
  GRAFANA_PANELID: ""
  GRAFANA_ALLFIELDSASTAGS: "ZmFsc2U="
  GRAFANA_MUTUALTLS: "ZmFsc2U="
  GRAFANA_CHECKCERT: "dHJ1ZQ=="
  GRAFANA_MINIMUMPRIORITY: ""

  # Fission Output
  FISSION_FUNCTION: ""
  FISSION_ROUTERNAMESPACE: "Zmlzc2lvbg=="
  FISSION_ROUTERSERVICE: "cm91dGVy"
  FISSION_ROUTERPORT: "ODA="
  FISSION_MINIMUMPRIORITY: ""
  FISSION_MUTUALTLS: "ZmFsc2U="
  FISSION_CHECKCERT: "dHJ1ZQ=="

  # Yandex Output
  YANDEX_ACCESSKEYID:  ""
  YANDEX_SECRETACCESSKEY: ""
  YANDEX_REGION: ""
  YANDEX_S3_ENDPOINT: ""
  YANDEX_S3_BUCKET: ""
  YANDEX_S3_PREFIX: ""
  YANDEX_S3_MINIMUMPRIORITY: ""

  # KafkaRest Output
  KAFKAREST_ADDRESS: ""
  KAFKAREST_VERSION: "Mg=="
  KAFKAREST_MINIMUMPRIORITY : ""
  KAFKAREST_MUTUALTLS : "ZmFsc2U="
  KAFKAREST_CHECKCERT : "dHJ1ZQ=="

  # WebUI Output
---
