apiVersion: v1
kind: Service
metadata:
  name: falcosidekick
  namespace: default
  labels:
    app.kubernetes.io/name: falcosidekick
    helm.sh/chart: falcosidekick-0.3.5
    app.kubernetes.io/instance: falcosidekick
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 2801
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: falcosidekick
    app.kubernetes.io/instance: falcosidekick
---
